name: EC2 Connection Test

on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            whoami
            pwd
            echo "Hello from EC2!"
            
            echo "=== System Information ==="
            uname -a
            echo -e "\n=== Distribution Info ==="
            lsb_release -a
            echo -e "\n=== CPU Info ==="
            cat /proc/cpuinfo | grep "model name" | head -n1
            
            echo "=== Disk Usage Report ===" > disk_report.txt
            date >> disk_report.txt
            echo -e "\nDisk Usage:" >> disk_report.txt
            df -h >> disk_report.txt
            echo -e "\nLargest Directories:" >> disk_report.txt

            memory_info=$(free -m)
            swap_info=$(swapon --show)
            echo "=== Memory Status ==="
            echo "$memory_info"
            echo -e "\n=== Swap Status ==="
            if [ -z "$swap_info" ]; then
              echo "No swap space configured"
            else
              echo "$swap_info"
            fi
            du -h /home/ubuntu | sort -rh | head -n5 >> disk_report.txt
            cat disk_report.txt
